### PR TITLE
use dropwizard 1.0

### PR DESCRIPTION
**Pull request by ngong**
refactored dependencies, use dropwizard 1.0

### CODE REVIEW

**Comment by ngong** [comment]
Dependencies are also cleaned up here ;)

**Comment by ngong** [comment]
ping @xiaodong-izettle

**Comment by xiaodong-izettle** [comment]
@ngong, maybe we could merge this one and #57, are dependencies like `jackson-databind` and `commons-codec` needed?

**Comment by ngong** [comment]
What #57 did are already included here.  `commons-codec` is used in test only. `jackson-databind` is not fully required, so I switched it to `jackson-annotations`

**Comment by xiaodong-izettle** [comment]
Added a commit to simplify dependency management, ping @ngong and @elhoo

**Comment by xiaodong-izettle** [comment]
Closes #54

**Comment by ngong** [comment]
Nice

**Comment by xiaodong-izettle** [comment]
We are good to go? :)

**Pull request merged**
